name: CollectAndUploadToYoutube
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip3 install -r ./requirements.txt
          sudo apt install php php-common gcc
          sudo apt install imagemagick
          sudo cp policy.xml /etc/ImageMagick*/

      - name: Run job
        run: python3 run.py

      - name: Config name
        run: git config user.name tejasmr

      - name: Config email
        run: git config user.email totejasmr@gmail.com

      - name: Track mp4
        run: git lfs track "*.mp4"

      - name: Add
        run: git add .

      - name: Commit
        run: git commit -m "Added logs"

      - name: Push
        run: git push
